# Build settings

markdown: kramdown
plugins:             [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag, jemoji]

port: 4000

include: ["_pages"]

sass:
  sass_dir: assets/css
  style: :nested

collections:
  courses:
    output: true
    title: Courses
    directory: ./_courses

  codes:
    output: true
    title: Codes
    directory: ./_codes

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		     "Vitor Sudbrack"
description:	     "The personal homepage of Vitor Sudbrack"
author:              "Vitor Sudbrack"
