# Build settings

markdown: kramdown
permalink: none
plugins:             [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag, jemoji]

port: 4000

sass:
  sass_dir: assets/css
  style: :nested

collections:
  courses:
    output: true
    title: Courses
  codes:
    output: true
    title: Codes

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		     "Vitor Sudbrack"
description:	     "The personal homepage of Vitor Sudbrack"
author:              "Vitor Sudbrack"
